### ISSUE TITLE
Proposal: better organizing of LLaMA-derived repos

### ISSUE THREAD

**Issue by nicognaW** [nichtdax/awesome-totally-open-chatgpt#15]
There are too many links in the related links section of the [tatsu-lab/stanford_alpaca item](https://github.com/nichtdax/awesome-totally-open-chatgpt#tatsu-labstanford_alpaca), which makes it difficult to understand what these links do.

We could improve it by making a clear sub-list for LLaMA-derived repos with concise descriptions.

**Comment by nichtdax** [comment]
I concur the fact that LLaMA is a sub-universe now. How should I rename the section?

**Comment by nicognaW** [comment]
Maybe "LLaMA-Related Projects" or "LLaMA-Derived Projects", just my thoughts as a non-native English speaker.

**Comment by nicognaW** [comment]
If you indeed want to update the structure but don't want any part to look incomplete, you can create a new branch. I can help you refine those introductions.

**Comment by nichtdax** [comment]
> As a side note, here might be another relevant one to add to the LLaMA list: https://github.com/nsarrazin/serge
> 
> Maybe include an explainer of what makes it a "sub-universe"? As I don't quite grasp the differences.

Compare to other projects, LLaMA has so much derivate works which are
- porting to other languages such as Rust, Cpp
- training with different datasets which have different preprocessing and gathering 
- different frontend projects

@ecker00

**Comment by nichtdax** [comment]
@nicognaW I have read carefully [LLaMA blog](https://ai.facebook.com/blog/large-language-model-llama-meta-ai/) and [Alpaca](https://crfm.stanford.edu/2023/03/13/alpaca.html). Because LLaMA is just the language model for being finetuned for other tasks, the "Related links" can be renamed to "LLaMA-derived projects" as you said before. All Reddit links can be removed.

**Comment by nichtdax** [comment]
Resolved by #14
