### ISSUE TITLE
Help for community support to collect and curate more open-source datasets to train instruction-following LLMs

### ISSUE THREAD

**Issue by yaodongC** [nichtdax/awesome-totally-open-chatgpt#16]
Hi Nicht, Inspired by your work, I am currently working on a project called **["awesome-instruction-dataset"](https://github.com/yaodongC/awesome-instruction-dataset)**, which is a curated collection of open-source datasets used for training chat-based LLMs. The primary goal of this repository is to provide a comprehensive list of datasets used for instruction tuning in various LLMs, making it easier for researchers and developers to access and utilize these resources.

I am reaching out to you because this project would achieve its full potential with community support to collect and curate more datasets. Your repo is one of the most influential repositories in compiling code base to train instruct-following LLms, and I believe that your support can make a significant impact on the success of this project.

It would be greatly appreciated if you could consider including a link to the "awesome-instruction-dataset" repository in your project's README.md

**Comment by nichtdax** [comment]
Closed by commit 1426c333f84327e55169004484b60149ac92609c
