### ISSUE TITLE
Add tavern ai

### ISSUE THREAD

**Issue by musikowskipawel** [nichtdax/awesome-totally-open-chatgpt#17]
https://github.com/TavernAI/TavernAI

**Comment by musikowskipawel** [comment]
Personally, I think it's the best open source alternative to chat gui.

**Comment by nicognaW** [comment]
First of all, thank you for contributing.

According to the document.

> Alternatives are projects featuring different instruct finetuned language models for chat. Projects are not counted if they are:
> 
> - Alternative frontend projects which simply call OpenAI's APIs.
> - Using language models which are not finetuned for human instruction or chat.

This repository you provided seems similar to the first case: an alternative frontend project that calls an LLM model like OpenAI's GPT series.

Although I think the current description is a little bit inaccurate (projects like frontend alternatives may be better called "LLM Applications" than just alternative projects), this project didn't provide any trained models or anything about that. So this project may not fit in this list, you could, by the way add it to other lists that aims collecting LLM Application projects.

**Comment by nichtdax** [comment]
@nicognaW 
> Alternative frontend projects which simply call OpenAI's APIs.
Here it is to filter the projects that **only** call OpenAI's APIs. And the goal of the list is to promote work that use other models.

**Comment by nichtdax** [comment]
For the case of TavernAI, I see they use KoboldAI and Pygmalion which are open source to my knowledge. Hence it's suitable for the list

**Comment by nichtdax** [comment]
Closed due to commit b1c3d2a3c48f0bbda7b745d24d50120ed4c401e5
