### ISSUE TITLE
add clue-ai/ChatYuan

### ISSUE THREAD

**Issue by alreadydone** [nichtdax/awesome-totally-open-chatgpt#18]
https://github.com/clue-ai/ChatYuan

I opened an [issue](https://github.com/clue-ai/ChatYuan/issues/25) there but got no response. Maybe someone here will volunteer to add it.

**Comment by nichtdax** [comment]
Can you provide the link to some kind of Readme *in English*?

**Comment by alreadydone** [comment]
The [official readme](https://github.com/clue-ai/ChatYuan#readme) contains English:

<blockquote>
ChatYuan large v2 is an open-source large language model for dialogue, supports both Chinese and English languages, and in ChatGPT style.

Based on the original functions of Chatyuan-large-v1, we optimized the model as follows:

-Added the ability to speak in both Chinese and English.

-Added the ability to refuse to answer. Learn to refuse to answer some dangerous and harmful questions.

-Added code generation functionality. Basic code generation has been optimized to a certain extent.

-Enhanced basic capabilities. The original contextual Q&A and creative writing skills have significantly improved.

-Added a table generation function. Make the generated table content and format more appropriate.

-Enhanced basic mathematical computing capabilities.

-The maximum number of length tokens has been expanded to 4096.

-Enhanced ability to simulate scenarios
</blockquote>

But there are some parts in the Chinese readme that isn't translated:

It uses the same technical approach as the v1 version and has been optimized in aspects such as fine-tuning data, RLHF, and chain-of-thoughts.

[online Demo(Huggingface)](https://huggingface.co/spaces/ClueAI/ChatYuan-large-v2)   | [online Demo(ModelScope, in Chinese)](https://modelscope.cn/studios/ClueAI/ChatYuan-large-v2) | [try online in Colab](https://colab.research.google.com/drive/1ZcLIJuemiojigrfjbsDMBWrX7JqXZX6I?usp=sharing)

The base model is [PromptCLUE](https://github.com/clue-ai/PromptCLUE) ([download](https://huggingface.co/ClueAI/PromptCLUE-base-v1-5)) (770M parameters) and they used more than 100M functional dialogue / multi-turn dialogue data to train. Their online service is based on models of dozens of billions of parameters, and they have plans to open-source larger models, according to [this article](https://mp.weixin.qq.com/s?__biz=MzA3MzI4MjgzMw==&mid=2650867789&idx=3&sn=72f69d87bd2e2ec3dff9e2b5c8f7b423&chksm=84e4cc33b3934525d908deefead8c5bbc0f23adea2d71e60c76cec00457707486b5be42016d4&scene=21#wechat_redirect) (in Chinese).

**Comment by nichtdax** [comment]
> But there are some parts in the Chinese readme that isn't translated:

I would prefer a fully English readme with example. But do you think we should just add [your comment](https://github.com/nichtdax/awesome-totally-open-chatgpt/issues/18#issuecomment-1492826662) in Related Links (if this project is added to the list)

**Comment by alreadydone** [comment]
Indeed it seems they are too focused on Chinese users (their company is centered around the CLUE benchmark as you can see from its name ClueAI, where C stands for Chinese), so that all examples provided are in Chinese. Maybe ChatYuan is not friendly enough to English users, and maybe it's not a good fit for this repo for this reason, but if you decide to add it, feel free to link to my comment above.

**Comment by nichtdax** [comment]
Resolved by 50ee7e28fc5fc309eabd3d9b156effb11459cb9d
