### ISSUE TITLE
Should h2ogpt be added to this list?

### ISSUE THREAD

**Issue by marco-ve** [nichtdax/awesome-totally-open-chatgpt#25]
[H2oGPT](https://github.com/h2oai/h2ogpt)  is published under Apache 2.0 AFAIK, and their cleaned OpenAssistant instruct dataset [is published](https://huggingface.co/datasets/h2oai/h2ogpt-oig-oasst1-instruct-cleaned-v1/tree/main).

**Comment by nichtdax** [comment]
It should

**Comment by nichtdax** [comment]
Resolved by 6f72ee8d276ba23f674f711297197f0403dd56a6
