### ISSUE TITLE
Consider adding web-llm

### ISSUE THREAD

**Issue by dinhanhx** [nichtdax/awesome-totally-open-chatgpt#26]
https://github.com/mlc-ai/web-llm 

> This project brings language model chats directly onto web browsers. Everything runs inside the browser with no server support and accelerated with WebGPU. We can bring a lot of fun opportunities to build AI assistants for everyone and enable privacy while enjoying GPU acceleration.

**Comment by nichtdax** [comment]
Resolved by c21805c634bc40a47b859c9a8ede287072613ddf
